# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fibonnacci():
    prev = [0, 1]
    while(True):
        n = sum(prev)
        prev[0] = prev[1]
        prev[1] = n
        yield n

s = 0

for fib in fibonnacci():
    if fib < 4000000:
        if fib % 2 == 0:
            s += fib
    else:
        break

print(s)